sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8

before_install:
  - docker pull behase/relumin-test
  - docker run -d behase/relumin-test
  - docker ps -a

script: mvn clean test -DargLine="-Dspring.profiles.active=travis"

cache:
  directories:
    - $HOME/.m2
